spring:
  application:
    name: resk-discovery

server:
  port: 8761

eureka:
  registration:
    enabled: false
  waitTimeInMsWhenSyncEmpty: 0
  server:
    enableSelfPreservation: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port:8761}/eureka/
